name: Trigger auto deployment for smart-knowledge-base-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/smart-knowledge-base-backend-AutoDeployTrigger-14a214a3-9e5d-4435-b327-5b2039d32ebe.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SMARTKNOWLEDGEBASEBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SMARTKNOWLEDGEBASEBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SMARTKNOWLEDGEBASEBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.SMARTKNOWLEDGEBASEBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SMARTKNOWLEDGEBASEBACKEND_REGISTRY_PASSWORD }}
          containerAppName: smart-knowledge-base-backend
          resourceGroup: Smart-Knowledge-Base
          imageToBuild: lindgeci/smart-knowledge-base-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


